Issue#45 be able to upload a video from youtube
MobileApps-Cascadia/gybitg-ios pull request #58
Opened 2019-11-20 22:24 UTC by Juanitaag1

the user can now upload a video from YouTube and it will be saved to the videoRepository

2019-11-20 23:39 UTC, MeyAyre approved these changes

2019-11-20 23:44 UTC, MeyAyre requested changes
Please remove your cocao pods from the PR.

2019-11-21 00:18 UTC, MeyAyre approved these changes

2019-11-21 00:18 UTC, jc-hayes approved these changes

2019-11-21 00:20 UTC, merged